version: '3.4'

services:
  archiesystem:
    image: olasek/archie
    build:
      context: .
      dockerfile: Archie\Dockerfile

  cryptoapi:
    image: olasek/cryptoapi
    build:
      context: .
      dockerfile: CryptoAPI\Dockerfile


  goldapi:
    image: olasek/goldapi
    build:
      context: .
      dockerfile: GoldAPI\Dockerfile

  exchangeapi:
    image: olasek/python
    ports:
    - "5000:5000"

  suwak:
    image: olasek/suwak
    build:
      context: .
      dockerfile: Suwak\Dockerfile


  diagram:
    image: olasek/diagram
    build:
      context: .
      dockerfile: Diagram\Dockerfile

