// <auto-generated />
using CryptoAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoAPI.Migrations
{
    [DbContext(typeof(CryptoAPIContext))]
    partial class CryptoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Archie.Models.TickerStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ask");

                    b.Property<decimal>("bid");

                    b.Property<decimal>("high");

                    b.Property<decimal>("last");

                    b.Property<decimal>("low");

                    b.Property<decimal>("volume");

                    b.Property<decimal>("vwap");

                    b.HasKey("Id");

                    b.ToTable("TickerStorage");
                });
#pragma warning restore 612, 618
        }
    }
}
